services:
  - type: web
    name: smart-farmer-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend
    envVars:
      - key: GEMINI_API_KEY
        sync: false
